### PR TITLE
fix: pipeline changes

### PR DESCRIPTION
**Pull request by MikeDobrzan**
fix: Release script configuration

### CODE REVIEW

**Review by parfeon — APPROVED** [review]
LGTM!

**Review by Xavrax — APPROVED** [review]
looks nice

**Comment by MikeDobrzan** [comment]
@pubnub-release-bot release

**Comment by kleewho** [comment]
Awesome work

**Comment by MikeDobrzan** [comment]
@pubnub-release-bot release as 7.0.0

**Comment by seba-aln** [comment]
Outstanding move!

**Review by budgetpreneur — APPROVED** [review]
LGTM 👍

**Review by techwritermat — APPROVED** [review]

**Pull request merged**
